- Numpy arrays are **homogeneous multidimensional** arrays ie. all of same type and have n>=2 dimensions
- Numpy = Numerical Python is an open source library
- Numpy arrays are called ndarray

In [1]:
import numpy as np

- Create numpy 1d-array from list

In [2]:
np.array([1,2,3])

array([1, 2, 3])

- Create 2d-array from list of list

In [3]:
np.array([[1,2,3],[5,1,3]])

array([[1, 2, 3],
       [5, 1, 3]])

- Numpy vs Python List
- Numpy = homogenous. ie. same data type
- Python List = heterogenous, general purpose

Properties of Numpy Array:
- All elements of same type
- Once created, size cant change
- Must be rectangular. ie. each row of 2d array must have same number of cols

- Access any element by index

In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
a[0]

np.int64(1)

- Slice indexing
- Slicing in array creates a **view** ie. it refers to the original data.
- Slicing in list creates a copy

In [6]:
a[1:3]

array([2, 3])

In [7]:
a = [1,2,3]

- Create 2d array using list of lists

In [8]:
list_of_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
list_of_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

- Indexing in list can be done in recursive manner

In [9]:
list_of_list[2][1]

10

In [10]:
a = np.array(list_of_list)

In [11]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- Indexing in array can be done using index only or like list

In [12]:
a[0,1]

np.int64(2)

In [13]:
a[0][1]

np.int64(2)

- Array Attributes
- Total Dimensions/Axis of Array
- Shape of Array

In [14]:
a.ndim

2

In [15]:
a.shape

(3, 4)

In [16]:
len(a.shape)==a.ndim

True

- Total elements stored in array

In [17]:
a.size

12

- Print type of each element (homogeneous)

In [18]:
a.dtype

dtype('int64')

- Create Basic Arrays

In [19]:
np.zeros(2)

array([0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

- Uninitialized Array

In [22]:
np.empty(5)

array([4.64774600e-310, 0.00000000e+000, 4.64715571e-310, 4.64715574e-310,
       2.37151510e-322])

- Create array with range of elements
- Can specify start, end and step size

In [23]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
np.array(range(4))

array([0, 1, 2, 3])

In [25]:
np.arange(4,10,2)

array([4, 6, 8])

In [26]:
np.array(range(4,10,2))

array([4, 6, 8])

- Create array with values spaced linearly over interval

In [27]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

- Specify dtype of nd array
- Default is float64
- Int Types: int8 / int16 / int32 and so on..

In [28]:
np.zeros((3,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

- Sort Array

In [29]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [30]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

- Concatenate Array

In [31]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [32]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.concat((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [257]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [258]:
x

array([[1, 2],
       [3, 4]])

In [259]:
y

array([[5, 6]])

In [261]:
concatenated_arr = np.concat((x,y))

In [262]:
concatenated_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [263]:
concatenated_arr.shape

(3, 2)

- Concatenation was along axis=0 ie axis=0 was extended

In [38]:
np.concat((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

- Concatenation along axis=1 can also be done

In [265]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [266]:
x.shape

(2, 2)

In [267]:
y = np.array([[5], [6]])
y

array([[5],
       [6]])

In [268]:
y.shape

(2, 1)

In [271]:
concatenated_arr = np.concat((x,y),axis=1)
concatenated_arr

array([[1, 2, 5],
       [3, 4, 6]])

In [272]:
concatenated_arr.shape

(2, 3)

- Size/Shape/Dim of Array

In [39]:
array_example = np.array(
[[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])

In [40]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [41]:
array_example.ndim

3

In [42]:
array_example.shape

(3, 2, 4)

In [43]:
array_example.size

24

- Reshape an array
- Size (ie. the number of elements) must remain same
- Elements are distributed right-index to left-index

In [44]:
a = np.arange(6)

In [45]:
a

array([0, 1, 2, 3, 4, 5])

In [46]:
a.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

- Convert 1d array to 2d (Add an axis)
- Row Vector: (1,b)
- Column Vector: (a,1)
- Matrix: (a,b)

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])

In [49]:
a.shape

(6,)

In [50]:
a.ndim

1

In [51]:
a2 = a[np.newaxis,:]

In [52]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [53]:
a2.shape

(1, 6)

In [54]:
row_vector = a[np.newaxis,:]

In [55]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [56]:
row_vector.shape

(1, 6)

In [57]:
col_vector = a[:,np.newaxis]

In [58]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [59]:
col_vector.shape

(6, 1)

- Expand the dimension at a specified position

In [60]:
a = np.array(range(1,7))

In [61]:
a

array([1, 2, 3, 4, 5, 6])

In [62]:
b = np.expand_dims(a,axis=1)

In [63]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [64]:
b.shape

(6, 1)

In [65]:
c = np.expand_dims(a,axis=0)

In [66]:
c

array([[1, 2, 3, 4, 5, 6]])

In [67]:
c.shape

(1, 6)

- Indexing/Slicing Numpy Array

In [68]:
data = np.array([1,2,3])

In [69]:
data[0]

np.int64(1)

In [70]:
data[0:2]

array([1, 2])

In [71]:
data[-2:]

array([2, 3])

- Boolean Indexing

In [72]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a.shape

(3, 4)

In [75]:
mask = a<7
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [76]:
a[mask]

array([1, 2, 3, 4, 5, 6])

In [77]:
divisible_by_2_mask = a%2==0

In [78]:
divisible_by_2_mask

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [79]:
a[divisible_by_2_mask]

array([ 2,  4,  6,  8, 10, 12])

- Specify multiple conditions using & and | operators

In [80]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
a[(a>2) & (a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

- use **np.nonzero** to get indices of non zero elements
- returns tuple: (row_indices,column_indices)
- need to zip to get element indices

In [82]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
b = np.nonzero((a>5)|(a<2))

In [84]:
list_of_coordinates = list(zip(b[0],b[1]))

In [85]:
list_of_coordinates

[(np.int64(0), np.int64(0)),
 (np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2)),
 (np.int64(1), np.int64(3)),
 (np.int64(2), np.int64(0)),
 (np.int64(2), np.int64(1)),
 (np.int64(2), np.int64(2)),
 (np.int64(2), np.int64(3))]

In [86]:
for cord in list_of_coordinates:
    print(a[cord])

1
6
7
8
9
10
11
12


- Slicing an array
- Upating a slice of array updates the original array

In [87]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr1 = a[3:8]

In [89]:
arr1

array([4, 5, 6, 7, 8])

In [90]:
arr1[1] = -1

In [91]:
arr1

array([ 4, -1,  6,  7,  8])

In [92]:
a

array([ 1,  2,  3,  4, -1,  6,  7,  8,  9, 10])

- Stack arrays vertically and horizontally

In [277]:
a1 = np.array([[1, 1],
               [2,2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [94]:
a1

array([[1, 1],
       [2, 2]])

In [95]:
a2

array([[3, 3],
       [4, 4]])

In [96]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [97]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

- Split array horizontally
- Provide number of sections to produce

In [98]:
x = np.arange(1, 25).reshape(2, 12)

In [99]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [100]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

- Numpy functions and operations like indexing/slicing return views (shallow copies) whenever possible for faster ops and saving memory
- Thus, modifying data in view modifies the original array!

In [101]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [102]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
b1 = a[0, :]

In [104]:
b1

array([1, 2, 3, 4])

In [105]:
b1[0] = 99

In [106]:
b1

array([99,  2,  3,  4])

In [107]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- Use copy to create a **deep** copy of array

In [108]:
b2 = a.copy()

In [109]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
b2[0,0] = 999

In [111]:
b2

array([[999,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [112]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- You can add arrays with a plus sign
- It performs elem-wise addition

In [113]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [114]:
data

array([1, 2])

In [115]:
ones

array([1, 1])

In [116]:
data + ones

array([2, 3])

- You can also do more elem wise operations

In [117]:
data - ones

array([0, 1])

In [118]:
data * ones

array([1, 2])

In [119]:
data / ones

array([1., 2.])

In [120]:
data // ones

array([1, 2])

In [121]:
data1 = data + ones
data1

array([2, 3])

In [122]:
data1 += ones

In [123]:
data1

array([3, 4])

- Sum of elements

In [124]:
a = np.array([1, 2, 3, 4])

In [125]:
a

array([1, 2, 3, 4])

In [126]:
a.sum()

np.int64(10)

- Sum over a particular axis

In [127]:
b = np.array([[1, 1], [2, 2]])

In [128]:
b

array([[1, 1],
       [2, 2]])

In [129]:
b.sum()

np.int64(6)

In [130]:
b.sum(axis=0)

array([3, 3])

In [131]:
b.sum(axis=1)

array([2, 4])

- Broadcasting = Operation b/w array and a scalar

In [132]:
data = np.array([1.0, 2.0])

In [133]:
data

array([1., 2.])

In [134]:
data*1.6

array([1.6, 3.2])

- Aggregation Functions in Numpy

In [135]:
data = np.array([1.0, 2.0])

In [136]:
data.sum()

np.float64(3.0)

In [137]:
data.min()

np.float64(1.0)

In [138]:
data.max()

np.float64(2.0)

In [139]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [140]:
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [141]:
a.shape

(3, 4)

In [142]:
a.sum()

np.float64(4.8595784)

In [143]:
a.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [144]:
a.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

- Creating Matrices Using List of List

In [145]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [146]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

- Arithmetic Operations on Matrix of Same Size

In [147]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

In [148]:
data

array([[1, 2],
       [3, 4]])

In [149]:
ones

array([[1, 1],
       [1, 1]])

In [150]:
data + ones

array([[2, 3],
       [4, 5]])

In [151]:
data - ones

array([[0, 1],
       [2, 3]])

In [152]:
data * ones

array([[1, 2],
       [3, 4]])

- Broadcasting a row or column vector on numpy array

In [153]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [154]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [155]:
data.shape

(3, 2)

In [156]:
ones_row = np.array([[1, 1]])

In [157]:
ones_row

array([[1, 1]])

In [158]:
ones_row.shape

(1, 2)

In [159]:
new_data = data + ones_row

In [160]:
new_data

array([[2, 3],
       [4, 5],
       [6, 7]])

In [161]:
new_data.shape

(3, 2)

In [162]:
ones_col = np.array([[1],[1],[1]])

In [163]:
ones_col

array([[1],
       [1],
       [1]])

In [164]:
ones_col.shape

(3, 1)

In [165]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [166]:
new_data = data + ones_col

In [167]:
new_data

array([[2, 3],
       [4, 5],
       [6, 7]])

In [168]:
new_data.shape

(3, 2)

- Random Number Generation in Numpy
- Random Numbers b/w [0,1]
- Random Integers Generation

In [169]:
rand_array = np.random.random((3,4))

In [170]:
rand_array

array([[0.52825408, 0.98254151, 0.01580191, 0.51891464],
       [0.24357966, 0.54858203, 0.75990005, 0.68487217],
       [0.06324329, 0.21166873, 0.12832539, 0.20446075]])

In [171]:
rand_int_array = np.random.randint(4,size=(3,4))

In [172]:
rand_int_array

array([[1, 1, 2, 0],
       [3, 3, 0, 0],
       [3, 2, 0, 1]])

In [173]:
rand_int_array.shape

(3, 4)

- Get Unique Elements in Array
- Freq Count of Unique Elements
- Indices of Unique Elements

In [174]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [175]:
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [176]:
a.shape

(15,)

In [177]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [178]:
unique_values, unique_indices = np.unique(a,return_index=True)

In [179]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [180]:
unique_indices

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [181]:
unique_values, freq_counts = np.unique(a,return_counts=True)

In [182]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [183]:
freq_counts

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

- Unique values and indices on 2d array
- Array is flattened here

In [184]:
a_2d = np.array([[1, 2, 3, 4], [5, 3, 7, 2], [9, 10, 11, 12], [1, 2, 3, 4]])

In [185]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  3,  7,  2],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [186]:
a_2d.shape

(4, 4)

In [187]:
uniq_vals, uniq_indices, freq_counts = np.unique(a_2d,return_index=True,return_counts=True)

In [188]:
uniq_vals

array([ 1,  2,  3,  4,  5,  7,  9, 10, 11, 12])

In [189]:
uniq_indices

array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11])

In [190]:
freq_counts

array([2, 3, 3, 2, 1, 1, 1, 1, 1, 1])

- Unique rows in the matrix

In [191]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  3,  7,  2],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [192]:
uniq_rows, uniq_row_indices, freq_counts_of_rows = np.unique(a_2d,
                                                 axis=0,
                                                 return_index=True,
                                                 return_counts=True)

In [193]:
uniq_rows

array([[ 1,  2,  3,  4],
       [ 5,  3,  7,  2],
       [ 9, 10, 11, 12]])

In [194]:
uniq_row_indices

array([0, 1, 2])

In [195]:
freq_counts_of_rows

array([2, 1, 1])

- Reshaping A Matrix
- In Reshape, Looping is done starting from the last index upto the first index
- For Array, last index = column and first index = row

In [196]:
data = np.array([[1,2],[3,4],[5,6]])

In [197]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [198]:
data.shape

(3, 2)

In [199]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
data.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [201]:
data.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

- Transpose of Matrix

In [202]:
arr = np.arange(6).reshape((2, 3))

In [203]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [205]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

- Reverse an Array

In [206]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [207]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

- Reversing a 2d array
- This reverses along all dimensions

In [209]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [210]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [211]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

- Reverse along one axis
- We can reverse only rows/cols

In [212]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [213]:
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [214]:
reversed_arr_cols = np.flip(arr_2d, axis=1)

In [215]:
reversed_arr_cols

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

- Flatten an Array
- flatten -> creates a copy
- ravel -> creates a view
- ravel is memory efficient but modification in flattened array results in modification of original array

In [216]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [217]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [218]:
flattened_array = x.flatten()

In [219]:
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [220]:
flattened_array[0] = 99

In [221]:
flattened_array

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [222]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [223]:
a2 = x.ravel()

In [224]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [225]:
a2[0] = 99

In [226]:
a2

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [227]:
x

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- Save and Load Numpy Arrays
- Save = saves numpy array as a binary object on desk (file extension: npy)
- Load = loads numpy array from binary file (file extension: npy)
- npy format is faster and smaller!
- npy format retains dtype information

In [228]:
a = np.array([1, 2, 3, 4, 5, 6])

In [229]:
a

array([1, 2, 3, 4, 5, 6])

In [230]:
np.save("filename",a)

In [231]:
a_from_disk = np.load("filename.npy")

In [232]:
a_from_disk

array([1, 2, 3, 4, 5, 6])

In [233]:
a_from_disk.dtype

dtype('int64')

- Save numpy array in human-readable text formats (csv/txt)
- But it **loses** dtype information!

In [234]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8],dtype=np.int32)

In [235]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [236]:
np.savetxt('new_file.txt', arr)

In [237]:
arr_from_disk = np.loadtxt("new_file.txt")

In [238]:
arr_from_disk

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [239]:
arr_from_disk.dtype

dtype('float64')

- Numpy array to csv files
- Use pandas dataframes!

In [240]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]],dtype="float32")

In [241]:
a

array([[-2.5828922 ,  0.43014842, -1.2408202 ,  1.595726  ],
       [ 0.9902783 ,  1.1715099 ,  0.9412571 , -0.14692469],
       [ 0.7698934 ,  0.8129968 , -0.95068425,  0.11769564],
       [ 0.20484035,  0.34784526,  1.969792  ,  0.5199284 ]],
      dtype=float32)

In [242]:
a.shape

(4, 4)

In [243]:
import pandas as pd
df = pd.DataFrame(a)

In [244]:
df

0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928

In [245]:
df.dtypes

0    float32
1    float32
2    float32
3    float32
dtype: object

In [246]:
df.to_csv("np.csv")